In [45]:
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 2, 1]])
C = np.concatenate((A,B.T), axis=1)
print(C)
print(f"Ранг исходной матрицы - {np.linalg.matrix_rank(A, 0000.1)}, ранг расширенной матрицы - {np.linalg.matrix_rank(C, 0000.1)}. \nСоответственно, система не имеет решений.\nТогда поменяем вектор правой части, чтобы система стала совместной. Например, вот так:")

X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Y = np.array([[4, 7, 10]])
Z = np.concatenate((X,Y.T), axis=1)
print(Z)
print(f"Ранги: {np.linalg.matrix_rank(X, 0000.1)}, {np.linalg.matrix_rank(Z, 0000.1)}")
print("Поскольку ранги теперь равны, но меньше числа неизвестных, решений будет бесконечно много (см. тетрадь).")

[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]
Ранг исходной матрицы - 2, ранг расширенной матрицы - 3. 
Соответственно, система не имеет решений.
Тогда поменяем вектор правой части, чтобы система стала совместной. Например, вот так:
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
Ранги: 2, 2
Поскольку ранги теперь равны, но меньше числа неизвестных, решений будет бесконечно много (см. тетрадь).
