In [49]:
import numpy as np
from scipy import linalg

A = np.array([[1, 2, 3], [2, 6, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

print(f"{P}\n\n{L}\n\n{U}")


[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

[[1.    0.    0.   ]
 [0.5   1.    0.   ]
 [0.25  0.625 1.   ]]

[[  4.      28.      73.    ]
 [  0.      -8.     -15.5   ]
 [  0.       0.      -5.5625]]
