In [1]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)

print(f"{A}\n\n{Q}\n\n{R}")

print(F"\n{np.dot(Q, R)}\n\n{np.dot(np.transpose(Q), Q)}")

R1 = R[:2, :2]
print(f"\n{R1}")

B1 = np.dot(np.transpose(Q), B)[:2]
print(f"\n{B1}")

X1 = np.linalg.solve(R1, B1)
print(f"\n{X1}")

X = np.append(X1, 0)
print(f"\n{X}")
np.linalg.norm(X)

print(f"\n{np.linalg.norm(np.dot(A, X) - B)}")

np.linalg.lstsq(A, B, rcond=None)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]

[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11164740e-15]]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

[[ 1.00000000e+00 -5.26517217e-16 -2.55176183e-16]
 [-5.26517217e-16  1.00000000e+00  3.37757775e-16]
 [-2.55176183e-16  3.37757775e-16  1.00000000e+00]]

[[-8.1240384  -9.6011363 ]
 [ 0.          0.90453403]]

[-1.21860576e+01  8.54871729e-15]

[1.50000000e+00 9.45096256e-15]

[1.50000000e+00 9.45096256e-15 0.00000000e+00]

1.2247448713915885


(array([ 1.25,  0.5 , -0.25]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]))